### ISSUE TITLE
Also port in the intro

### ISSUE THREAD

**Issue by shahoob** [amykatname/smbcd#7]
Title should explain it all.

**Comment by amykatname** [comment]
as I told shahoob, I commented out the original stabyourself intro, even tho it can be skipped, Id rather make it so you don't have to wait to play, atleast for now, if this is continued to have the 40ish levels, and so be more like a full game rather than a demo, then sure

**Comment by shahoob** [comment]
pretty sure wontfix means "don't bother us about this, we ain't gonna do shit about this" and not "maybe later", it's still planned
it would be stale though

**Comment by shahoob** [comment]
I put in the FamicomCD logo successfully, although it isn't the exact one from the demo. don't care lol
There's still the "SMBCD TEAM Presents" screen soooo uhhhhhhhhhhhh

**Comment by shahoob** [comment]
forgot that when skipping the intro it abruptly ends, not even a fade or a delay

**Comment by shahoob** [comment]
still didn't fix that issue i mentioned but other than that it should be complete\nalso made it pixel perfect with the help of @amykatname
